name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v5
      - name: Get Go version
        id: go-version
        run: echo "go-version=$(grep -o 'go [0-9]\+\.[0-9]\+' go.mod | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ steps.go-version.outputs.go-version }}
      - name: Test
        run: make test
